export type Page =
  | 'dashboard'
  | 'overview'
  | 'codex'
  | 'github-copilot'
  | 'windsurf'
  | 'kiro'
  | 'proxy'
  | 'kiro-proxy'
  | 'antigravity-proxy'
  | 'codex-instances'
  | 'instances'
  | 'accounts'
  | 'fingerprints'
  | 'wakeup'
  | 'settings';
